CREATE TABLE `books`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `author` VARCHAR(255) NOT NULL,
    `abstract` TEXT NULL,
    `image` VARCHAR(255) NULL,
    `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE `reviews`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `book_id` BIGINT UNSIGNED NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `vote` TINYINT NOT NULL,
    `text` TEXT NULL,
    `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE
    `reviews` ADD CONSTRAINT `reviews_book_id_foreign` FOREIGN KEY(`book_id`) REFERENCES `books`(`id`);